Fix lastArchivePath,lastFilepath memory management
The project can't be archived due to `-Wobjc-property-assign-on-object-type` flagging a potential memory management error defining `lastArchivePath` and `lastFilepath`. 

Both properties are defined as `assign` but they contain object references. A `copy` would probably work better in this case.

```
/Users/danielgarcia/.../Carthage/Checkouts/UnrarKit/Classes/URKArchive.mm:54:1: error: 'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained' [-Werror,-Wobjc-property-assign-on-object-type]
@property (assign) NSString *lastArchivePath;
^
/Users/danielgarcia/.../Carthage/Checkouts/UnrarKit/Classes/URKArchive.mm:55:1: error: 'assign' property of object type may become a dangling reference; consider using 'unsafe_unretained' [-Werror,-Wobjc-property-assign-on-object-type]
@property (assign) NSString *lastFilepath;
^
2 errors generated.
```